language: node_js
os: linux
node_js:
  - "node"
  - "12"
  - "10"
jobs:
  include:
    - stage: test
      if: branch = master OR tag IS present
      install:
        - npm install
      script:
        - npm test
    - stage: deploy
      if: tag IS present
      script: skip
      deploy:
        cleanup: true
        provider: npm
        email: backend.services@zippadd.com
        api_token:
          secure: "UC3AopwhEkxOrHI2rMtIKj0nTYW0+DN65aqzj/gFFVNl3d9q4Ug6ojI/ehVZk1F9+EdlxJ+dz9sI5OacMX83z7GsnXvswES3CqToSOQFf7h4vE2Bue0LY2TSmNejcjdFBnmwCODKPYxXxgEft7hFVd64GavjrBwBHn5lMudCEzrOV1eakNx0AytirLfowzB/lIIogifMxHhubVkjrCHXMZcGFSAbtOEZqP/BK5d/jOU3XhUQc25pECqelKWjqJK7q5NXQj4yqvnZ4pESUpf3AKxhB5AdM9/tDRwFLzmdK1swoMXYL/rj3qNgbKPtXE+Q1LDyHSEB99wPNFtgfcnkbTpEjnmklNAVScuyOOuVZ93Vu8RNs8QL5VY0vnSEEU/eASh8rbfxbOWIbktgft9BaXgNWljXh4i8xd5GjkUxsJO5cDfdEMtbM/yy48pUnNqOdZdp+jGDLWsjVElGdflOxD4z4xl1eo/gpEtW8Yq2kwj4+hV089tQATjWThAwQcVZqFdjSkXNYiv/jfknv47klVCRst1plsatCpX7+HXsLCnw37hWDF0lU94o5OmSXg4aR6w9CM9j8PrhxTpNz+KFcNcr2/B7npWR6BSRZiLQfOT4mno0+y2Td6NiK58ISwts48jOLU+fNVvER5n7MDazFe5mZXyuxPo5LQEyno45DZU="
        on:
          tags: true
          repo: zippadd/cfdeploy
          condition: $(git fetch origin master:master && git branch --contains $TRAVIS_TAG | grep '^[\*| ] master$')
