language: node_js
os: linux
node_js:
  - "node"
  - "12"
  - "10"
jobs:
  include:
    - stage: test
      if: branch = master OR tag IS present
      install:
        - npm install
      script:
        - npm test
    - stage: deploy
      if: tag IS present
      script: skip
      deploy:
        cleanup: true
        provider: npm
        email: backend.services@zippadd.com
        api_key:
          secure: "hBzAYhXEcjYutQHBYNTqVXINjBe0HvWzBKy/rHmxuzdSVEXhH3pgqWnXSCNNnnh3ffXra/bDvCKBBC6Pi3AlXZpnEjxmmcOieLbE7EzjnHRnwBilL071VborPqYfDQXCSPlM44v7n9hGlSSr1nSrdaoIjIerEqK7mf4ty68BI690+OOnU7maGlxsJRyqV0r7DYgwEL1o600bJvtS/sGvU22+H5SVz0uURITmfVaexJOhL7NLZffEDrqP7b/pFhRE32RPhZxp53O4TDHNNBJ4kGHbBJ9O81OYta5xgONljgCABiAidaWTZXZuythbcmUAfRIYxl+EDLDx8OO2JqGZWajHiLXjDmfmvdf6yEPb2L5AUvONEwbVRz2WUM9B5zHM4E+s+hywo4jSh+S9HSN2cUjP8bkeyN5sLd44LptDjpa/RKhUt4mo+IdLEw3fvOYqBewkBeopvg+knch5Y4qktmNx5no2Bc3iJfRRhbJBmoqlzkrCCLAuUTrETSo3d6c0PfAMJdIQ6+R8jj9AP/0/M7/cgcAEV7sQzgnp0XXzylz+cIckzBh2xIjpBVB8ql06PCdjV2Mw49Cd/GeqsBMswRk7IKc4JBUsvpfUGtvKgRVhd8XnLUI7app+xhGzJMkkJvkWJyig8xRqONuBLm6cZqbn1VPFjqf7fLNle0CdXhs="
        on:
          tags: true
          repo: zippadd/cfdeploy
          condition: $(git fetch origin master:master && git branch --contains $TRAVIS_TAG | grep '^[\*| ] master$')
