language: node_js
os: linux
node_js:
  - "node"
  - "14"
  - "12"
  - "10"
jobs:
  include:
    - stage: test
      if: branch = master OR tag IS present
      install:
        - npm ci
      script:
        - npm test
    - stage: deploy
      if: tag IS present
      script: skip
      deploy:
        cleanup: true
        provider: npm
        email: backend.services@zippadd.com
        api_key:
          secure: "BFv6xLMU+4AUnIktiuAcgJb8KhwYKNiZF1LJWL8IAQBbRSP/c48Ul9VJMCyzgCsPtlKic1taaPz/G7AtrYMxisK/Px/vIt6CAEw2g+XQu9AsNks4dcPMkTajhdrgiVLSIIDyFk2pLZJYpHs8ZzNZtq4pmEYMQZt6nXf9qRpVAMEyQb/TGCSAwE/59iZRsrQJZwgjXpOpQaNxXQWdZ6XwNuN5Fum5EvTlhqtwhvJJG9A7VA2oquSrgxC/PNNMfHakGLJGS4Z79DNcFnXr4b02+i/wdpMHBxaFoS0hzYg3e4e7EzRBR31DDJd4KqRx5rRZh8Q16FtiyI7DyTDDros5MBkPEv0rQURYnHmo5yj9sTI573UXhteU84WS9h+fQ2I4HCiym7zrLCOLngk36ya4TR8dbMqHbwOJt0az62EQxQdfLmuqR6055mhf6Gf9Y/RcQv3uWX+E0/ZV1i37k1EvzCK9y09gVwMvguf7Eh6AxsoQfOed+Cix0wtdHpiE7PTsBLZVOyl9FxhooRHpplcYhJ1EIrzEQy3Z5WubLyAiLWhuCXjGnqsigpsNJxJodaAHcuyveyjACbNn5Agu0qJLIjliRHonpCEZGMQ1/iJnEBtWwoBGl+ztzPmZaOccHJTBqhtbs/lJ/QENv6Y3Me0orYhix/mmUdNnx1375Z9tTcU="
        on:
          tags: true
          repo: zippadd/cfdeploy
          condition: $(git fetch origin master:master && git branch --contains $TRAVIS_TAG | grep '^[\*| ] master$')
